/* The two-command comparison route, run on the vendored kernels in hexagon-sim
 * with the parameters the HOST EMITTER produced.
 *
 * The point is not to re-measure htp_ops_select at one byte -- hexagon-cmpgate
 * did that, and this file is not a second copy of its claim. It is that the
 * emitter's parameter vector is the vector the DSP was measured with. A
 * hand-written runner asserts about a call someone typed; this one is handed a
 * header the test generated from the blob a real export produced, so a
 * transposed pair, a wrong op type or a one-byte value declared two bytes wide
 * cannot pass by agreeing with itself.
 *
 * The two commands are driven through the dispatcher's own entry points, in the
 * order the blob lists them, and the bytes between the three buffers are the
 * blob's own: the flag buffer is what the first command wrote and the two
 * one-byte sources are read from the weight section at the offsets the blob
 * records.
 */
#include <stdint.h>
#include <stdio.h>

/* Generated by the test: the parameter vector of each command, and the bytes of
 * the weight section at the offsets the blob recorded for the select's two
 * sources. Nothing below is a literal. */
#include "gtlt_params.h"

extern "C" int htp_ops_binary_elementwise(uint8_t *dst, uint8_t *src0, uint8_t *src1,
                                           int32_t outSize, int32_t in0Size,
                                           int32_t in1Size, int32_t opType,
                                           int32_t bytes, int32_t inputBytes,
                                           int32_t inputIsFloat, int32_t outputIsFloat,
                                           const int32_t *broadcastParams,
                                           int32_t broadcastParamCount);
extern "C" int htp_ops_select(uint8_t *dst, uint8_t *cond_ptr, uint8_t *src1_ptr,
                              uint8_t *src2_ptr, int32_t outSize, int32_t condSize,
                              int32_t in1Size, int32_t in2Size, int32_t bytes,
                              int32_t condBytes, int32_t channelSize, int32_t innerSize);

#define N 16
#define VEC 128

/* Sixteen pairs chosen for their order relations rather than their values: the
 * two signed zeros, a NaN against itself, each infinity against itself, and the
 * fp16 extremes. Indices 1, 4, 5 and 6 are where a subtract-based route would
 * answer differently, and they are in the list for that reason. */
static const float A_IN[N] = {0.0f,  -0.0f,  1.0f,  -1.0f,  0.0f / 0.0f, 1.0f / 0.0f,
                              -1.0f / 0.0f, 2.0f, -2.0f, 0.5f, -0.5f, 3.0f, 1.0e-4f,
                              -1.0e-4f, 65504.0f, -65504.0f};
static const float B_IN[N] = {0.0f,  0.0f,  1.0f,  1.0f,  0.0f / 0.0f, 1.0f / 0.0f,
                              -1.0f / 0.0f, 1.0f, -1.0f, 0.25f, -0.25f, 3.0f, 1.0e-4f,
                              1.0e-4f, -65504.0f, 65504.0f};

static _Float16 A[N] __attribute__((aligned(VEC)));
static _Float16 Bv[N] __attribute__((aligned(VEC)));
static _Float16 Flags[N] __attribute__((aligned(VEC)));
static uint8_t Out[N] __attribute__((aligned(VEC)));
static_assert(__alignof__(A) == VEC, "A is read a vector at a time");
static_assert(__alignof__(Bv) == VEC, "Bv is read a vector at a time");
static_assert(__alignof__(Flags) == VEC, "Flags is written a vector at a time");
static_assert(__alignof__(Out) == VEC, "Out is written a vector at a time");

static void print_h(const char *tag, const _Float16 *v, int n) {
  printf("%s", tag);
  for (int i = 0; i < n; ++i) printf(" %04x", ((const uint16_t *)v)[i]);
  printf("\n");
}

static void print_b(const char *tag, const uint8_t *v, int n) {
  printf("%s", tag);
  for (int i = 0; i < n; ++i) printf(" %02x", v[i]);
  printf("\n");
}

int main(void) {
  for (int i = 0; i < N; ++i) {
    A[i] = (_Float16)A_IN[i];
    Bv[i] = (_Float16)B_IN[i];
  }
  print_h("A", A, N);
  print_h("B", Bv, N);

  /* Command one, with the blob's own head and broadcast tail. The dispatcher
   * reads the tail from params[8], which is the rank. */
  const int32_t *tail = kCompareParams + 8;
  int r0 = htp_ops_binary_elementwise((uint8_t *)Flags, (uint8_t *)A, (uint8_t *)Bv,
                                      kCompareParams[0], kCompareParams[1], kCompareParams[2],
                                      kCompareParams[3], kCompareParams[4], kCompareParams[5],
                                      kCompareParams[6], kCompareParams[7], tail,
                                      kCompareParams[8]);
  printf("BRCMP %08x\n", (unsigned)r0);
  print_h("FLAGS", Flags, N);

  /* Command two, with the blob's parameter vector and the blob's own bytes for
   * its two sources, copied out of the weight section at the offsets the blob
   * recorded for them. */
  uint8_t on = kSelectSources[kOnOffset];
  uint8_t off = kSelectSources[kOffOffset];
  printf("SRC %02x %02x\n", on, off);
  int r1 = htp_ops_select(Out, (uint8_t *)Flags, &on, &off, kSelectParams[0],
                          kSelectParams[1], kSelectParams[2], kSelectParams[3],
                          kSelectParams[4], kSelectParams[5], kSelectParams[6],
                          kSelectParams[7]);
  printf("SELRC %08x\n", (unsigned)r1);
  print_b("GT", Out, N);

  /* The same command pair for LESS, so both op types are run rather than one
   * read out of a table. */
  int r2 = htp_ops_binary_elementwise((uint8_t *)Flags, (uint8_t *)A, (uint8_t *)Bv,
                                      kLessParams[0], kLessParams[1], kLessParams[2],
                                      kLessParams[3], kLessParams[4], kLessParams[5],
                                      kLessParams[6], kLessParams[7],
                                      kLessParams + 8, kLessParams[8]);
  printf("LSCMP %08x\n", (unsigned)r2);
  int r3 = htp_ops_select(Out, (uint8_t *)Flags, &on, &off, kSelectParams[0],
                          kSelectParams[1], kSelectParams[2], kSelectParams[3],
                          kSelectParams[4], kSelectParams[5], kSelectParams[6],
                          kSelectParams[7]);
  printf("LSSEL %08x\n", (unsigned)r3);
  print_b("LT", Out, N);
  return 0;
}
