/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include <executorch/backends/hexagon/runtime/hexagon_driver.h>

#include <climits>
#include <cstdio>
#include <cstring>

#include <dlfcn.h>

#include <AEEStdErr.h>
#include <dsp_capabilities_utils.h>
#include <remote.h>
#include <rpcmem.h>

// Generated by qaic from the same IDL the skel is built from, so the handle
// numbers on both sides cannot drift.
#include "htp_ops.h"
#include "hexagon_skel_provenance.h"

namespace executorch::backends::hexagon {

namespace {

constexpr const char* kSkelUriPrefix = "file:///";
constexpr const char* kSkelUriSuffix = "?htp_ops_skel_handle_invoke&_modver=1.0";
// Must match the skel target's OUTPUT_NAME in skel/CMakeLists.txt.
// The capability's low byte holds the arch as hex digits, so v79 arrives as
// 0x79 and has to be printed back as "79" -- %u would ask for v121.
constexpr const char* kSkelNameFormat = "libhex-htp-skel-v%02X.so";
constexpr const char* kDsprpcLib = "libcdsprpc.so";

// FastRPC's default is no RPC timeout, which is what turns a DSP-side hang into
// an unkillable wait: the invoke never returns, so no error ever reaches the
// caller. Registering the v2 notification struct arms a per-PD timeout so the
// same hang comes back as AEE_EEXPIRED. 10 s sits above a slow but legitimate
// first prefill, so only a real hang trips it.
constexpr uint32_t kRpcTimeoutMs = 10000;
// AEE_EOFFSET is 0 on HLOS, so a DSP-side code that reaches us unscaled does
// not compare equal to its AEE_EEXPIRED spelling.
constexpr AEEResult kAeeExpiredDsp = static_cast<AEEResult>(0x8000040cu);

Error ToError(AEEResult err, const char* what) {
  if (err == AEE_SUCCESS) {
    return Error::Ok;
  }
  if (err == AEE_EEXPIRED || err == kAeeExpiredDsp) {
    std::fprintf(
        stderr,
        "[hexagon] %s exceeded the %u ms RPC timeout (AEE_EEXPIRED)\n",
        what,
        (unsigned)kRpcTimeoutMs);
  }
  std::fprintf(stderr, "[hexagon] %s failed: 0x%08x\n", what, (unsigned)err);
  return Error::Internal;
}

// Picks the skel matching the device's Hexagon arch. A mismatched skel would
// run kernels compiled for a different HVX width, which shows up as corrupted
// numbers rather than a load failure, so the arch is verified after loading.
std::string SelectSkel(int domain_id, uint32_t* expected_arch) {
  uint32_t capability = 0;
  *expected_arch = 0;

  int err = get_hex_arch_ver(domain_id, &capability);
  unsigned int arch = capability & 0xff;
  if (err != AEE_SUCCESS || arch == 0) {
    std::fprintf(
        stderr,
        "[hexagon] get_hex_arch_ver failed: 0x%08x capability=0x%x\n",
        (unsigned)err,
        capability);
    return std::string();
  }

  *expected_arch = arch;
  char name[64];
  std::snprintf(name, sizeof(name), kSkelNameFormat, arch);
  return name;
}

const char* StatusName(remote_rpc_status_flags_t status) {
  switch (status) {
    case FASTRPC_USER_PD_UP:
      return "USER_PD_UP";
    case FASTRPC_USER_PD_EXIT:
      return "USER_PD_EXIT";
    case FASTRPC_USER_PD_FORCE_KILL:
      return "USER_PD_FORCE_KILL";
    case FASTRPC_USER_PD_EXCEPTION:
      return "USER_PD_EXCEPTION";
    case FASTRPC_DSP_SSR:
      return "DSP_SSR";
    case FASTRPC_INTERNAL_STATUS_RESERVED_1:
      return "INTERNAL_STATUS_RESERVED_1";
    case FASTRPC_USERPD_TIMEOUT:
      return "USERPD_TIMEOUT";
    default:
      return "UNKNOWN";
  }
}

// Called by FastRPC on its own thread: print and return. Blocking here, or
// re-entering FastRPC from here, would wedge a thread the library owns.
int RpcStatusNotify(
    void* context,
    int domain,
    int session,
    remote_rpc_status_flags_t status) {
  (void)context;
  std::fprintf(
      stderr,
      "[hexagon] pd notification: domain=%d session=%d status=%s(%d)\n",
      domain,
      session,
      StatusName(status),
      (int)status);
  return AEE_SUCCESS;
}

// Returns whether the timeout is armed. The caller continues either way: on a
// kernel that does not implement the v2 struct, the failure code is the answer.
bool ArmRpcTimeout(int domain_id) {
  struct remote_rpc_notif_register_v2 notif;
  notif.context = nullptr;
  notif.domain = domain_id;
  notif.notifier_fn = RpcStatusNotify;
  notif.timeout = kRpcTimeoutMs;

  const AEEResult err = remote_session_control(
      FASTRPC_REGISTER_STATUS_NOTIFICATIONS, &notif, sizeof(notif));
  if (err != AEE_SUCCESS) {
    std::fprintf(
        stderr,
        "[hexagon] rpc timeout NOT armed: registering status notifications "
        "with a %u ms timeout on domain %d failed: 0x%08x\n",
        (unsigned)kRpcTimeoutMs,
        domain_id,
        (unsigned)err);
    return false;
  }
  std::fprintf(
      stderr,
      "[hexagon] rpc timeout armed on domain %d: %u ms\n",
      domain_id,
      (unsigned)kRpcTimeoutMs);
  return true;
}

// Runs after an RPC call timed out, to answer one question: is the session still
// usable, or does it have to be rebuilt? A wedged session makes any later invoke
// hang too, so this is only safe to attempt *because* Open() armed the RPC
// timeout: each probe call is bounded by kRpcTimeoutMs instead of blocking
// forever. Worst case is two extra timeouts on top of the one that just expired.
//
// htp_ops_getInfo (IDL method 6) is the probe of choice: it takes no VTCM guard
// and only reads VTCM/HVX numbers back, so it cannot repeat the work of the call
// that hung and cannot double-apply a stateful operation.
//
// The second probe opens a new handle instead of closing the first: Close() frees
// every live arena and would corrupt the caller's bookkeeping in the middle of a
// failure, while a second handle in the same PD answers the same question -- does
// a fresh session work? -- and is closed again immediately.
void ProbeAfterTimeout(
    HexagonDriver& driver,
    int domain_id,
    uint64_t wedged_handle,
    AEEResult original) {
  auto scratch = driver.Alloc(4096);
  if (!scratch.ok()) {
    std::fprintf(stderr, "[hexagon] post-timeout probe: no scratch buffer\n");
    return;
  }
  const int fd = scratch->fd;
  const int offset = (int)scratch->bias;

  const AEEResult same = htp_ops_getInfo(wedged_handle, fd, offset);
  std::fprintf(
      stderr,
      "[hexagon] post-timeout probe 1/2 (same handle): getInfo -> 0x%08x%s\n",
      (unsigned)same,
      (same == AEE_EEXPIRED || same == kAeeExpiredDsp)
          ? "  [timed out: this session is wedged]"
          : "");

  // Probe 2 runs unconditionally. Probe 1 only says whether *this* handle is
  // still alive, while probe 2 answers the question the probe exists for: does a
  // fresh session work, i.e. can a reboot be avoided? A wedged handle is exactly
  // when that answer matters, and every probe call is bounded by the timeout.
  AEEResult fresh = AEE_SUCCESS;
  bool ran_fresh = false;
  {
    uint32_t probe_arch = 0;
    domain* probe_domain = get_domain(domain_id);
    const std::string skel_name = SelectSkel(domain_id, &probe_arch);
    if (probe_domain == nullptr || skel_name.empty()) {
      std::fprintf(
          stderr,
          "[hexagon] post-timeout probe 2/2: cannot rebuild the skel URI\n");
    } else {
      // The URI Open() built: same skel, same domain, so the same PD.
      const std::string uri = std::string(kSkelUriPrefix) + skel_name +
          kSkelUriSuffix + probe_domain->uri;
      uint64_t fresh_handle = 0;
      fresh = htp_ops_open(uri.c_str(), &fresh_handle);
      ran_fresh = true;
      if (fresh == AEE_SUCCESS) {
        fresh = htp_ops_getInfo(fresh_handle, fd, offset);
        // The wedged handle stays open: Close() owns it.
        htp_ops_close(fresh_handle);
      }
      std::fprintf(
          stderr,
          "[hexagon] post-timeout probe 2/2 (fresh session on the same PD): "
          "open+getInfo -> 0x%08x%s\n",
          (unsigned)fresh,
          fresh == AEE_SUCCESS ? "  [a fresh session works: no reboot needed]"
                               : "");
    }
  }

  if (ran_fresh) {
    std::fprintf(
        stderr,
        "[hexagon] post-timeout probe: original=0x%08x same_handle=0x%08x "
        "fresh_session=0x%08x\n",
        (unsigned)original,
        (unsigned)same,
        (unsigned)fresh);
  } else {
    std::fprintf(
        stderr,
        "[hexagon] post-timeout probe: original=0x%08x same_handle=0x%08x "
        "fresh_session=unavailable\n",
        (unsigned)original,
        (unsigned)same);
  }
  driver.Free(scratch->ptr);
}

} // namespace

void HexagonDriver::ResolveCacheOps() {
  void* lib = dlopen(kDsprpcLib, RTLD_NOW | RTLD_LOCAL);
  if (lib == nullptr) {
    std::fprintf(
        stderr, "[hexagon] dlopen(%s) failed: %s\n", kDsprpcLib, dlerror());
    return;
  }
  cache_flush_ = reinterpret_cast<CacheOpFn>(dlsym(lib, "rpcmem_cache_flush"));
  cache_invalidate_ =
      reinterpret_cast<CacheOpFn>(dlsym(lib, "rpcmem_cache_invalidate"));
  cached_ = cache_flush_ != nullptr && cache_invalidate_ != nullptr;
  // The library stays loaded for the process: the FastRPC handle is backed by
  // it and dlclosing it here would strand the session.
}

Result<HexagonDriver> HexagonDriver::Create(int domain_id) {
  HexagonDriver driver;
  driver.domain_id_ = domain_id;
  ET_CHECK_OK_OR_RETURN_ERROR(driver.Open());
  return driver;
}

Error HexagonDriver::Open() {
  domain* dsp_domain = get_domain(domain_id_);
  if (dsp_domain == nullptr) {
    std::fprintf(stderr, "[hexagon] no domain %d on this device\n", domain_id_);
    return Error::Internal;
  }

  const std::string skel_name = SelectSkel(domain_id_, &skel_arch_);
  if (skel_name.empty()) {
    return Error::Internal;
  }
  const std::string uri = std::string(kSkelUriPrefix) + skel_name +
      kSkelUriSuffix + dsp_domain->uri;

  // The skel is unsigned, so FastRPC has to put the session in an unsigned
  // protection domain before the module is loaded. Without this the DSP
  // rejects the load with AEE_EFAILED (0xffffffff).
  {
    remote_rpc_control_unsigned_module unsigned_pd;
    unsigned_pd.domain = domain_id_;
    unsigned_pd.enable = 1;
    const AEEResult pd_err = remote_session_control(
        DSPRPC_CONTROL_UNSIGNED_MODULE, &unsigned_pd, sizeof(unsigned_pd));
    if (pd_err != AEE_SUCCESS) {
      std::fprintf(
          stderr,
          "[hexagon] failed to enable the unsigned protection domain on domain "
          "%d: 0x%08x\n",
          domain_id_,
          (unsigned)pd_err);
      return Error::Internal;
    }
  }

  // Arming the RPC timeout is deliberately unconditional: it is the only way
  // a DSP-side hang can surface as an error instead of an infinite wait.
  ArmRpcTimeout(domain_id_);

  AEEResult err = htp_ops_open(uri.c_str(), &handle_);
  if (err != AEE_SUCCESS) {
    std::fprintf(
        stderr,
        "[hexagon] failed to load skel %s: 0x%08x\n",
        skel_name.c_str(),
        (unsigned)err);
    handle_ = 0;
    return Error::Internal;
  }

  uint32_t reported_arch = 0;
  err = htp_ops_get_skel_arch(handle_, &reported_arch);
  if (err != AEE_SUCCESS || reported_arch != skel_arch_) {
    std::fprintf(
        stderr,
        "[hexagon] skel arch mismatch: device V%02X, skel V%02X\n",
        skel_arch_,
        reported_arch);
    Close();
    return Error::Internal;
  }

  uint32_t reported_source_id[4] = {0, 0, 0, 0};
  err = htp_ops_get_skel_source_id(
      handle_,
      &reported_source_id[0],
      &reported_source_id[1],
      &reported_source_id[2],
      &reported_source_id[3]);
  if (err == AEE_EUNSUPPORTED) {
    std::fprintf(
        stderr,
        "[hexagon] skel predates the provenance RPC; rebuild and redeploy "
        "the skel from this source tree\n");
    Close();
    return Error::Internal;
  }
  if (err != AEE_SUCCESS || !skel_source_id_matches(reported_source_id)) {
    std::fprintf(
        stderr,
        "[hexagon] skel source ID mismatch: expected %s, got %08x%08x%08x%08x "
        "(RPC 0x%08x)\n",
        HEXAGON_SKEL_SOURCE_ID_TEXT,
        reported_source_id[3],
        reported_source_id[2],
        reported_source_id[1],
        reported_source_id[0],
        (unsigned)err);
    Close();
    return Error::Internal;
  }

  // Without a latency hint the DSP is parked between ops and per-op latency
  // dominates.
  struct remote_rpc_control_latency latency;
  latency.enable = RPC_PM_QOS;
  latency.latency = 50;
  err = remote_handle64_control(
      handle_, DSPRPC_CONTROL_LATENCY, &latency, sizeof(latency));
  if (err != AEE_SUCCESS) {
    std::fprintf(
        stderr, "[hexagon] RPC_PM_QOS unavailable: 0x%08x\n", (unsigned)err);
  }

  ResolveCacheOps();

  ET_CHECK_OK_OR_RETURN_ERROR(
      ToError(htp_ops_init_backend(handle_), "init_backend"));
  return Error::Ok;
}

void HexagonDriver::Close() {
  for (auto& entry : allocations_) {
    const Allocation& alloc = entry.second;
    fastrpc_munmap(domain_id_, alloc.fd, alloc.base, alloc.size);
    rpcmem_free(alloc.base);
  }
  allocations_.clear();

  if (handle_ != 0) {
    htp_ops_close(handle_);
    handle_ = 0;
  }
}

HexagonDriver::~HexagonDriver() {
  Close();
}

HexagonDriver::HexagonDriver(HexagonDriver&& other) noexcept
    : domain_id_(other.domain_id_),
      handle_(other.handle_),
      skel_arch_(other.skel_arch_),
      cached_(other.cached_),
      cache_flush_(other.cache_flush_),
      cache_invalidate_(other.cache_invalidate_),
      allocations_(std::move(other.allocations_)) {
  other.handle_ = 0;
}

HexagonDriver& HexagonDriver::operator=(HexagonDriver&& other) noexcept {
  if (this != &other) {
    Close();
    domain_id_ = other.domain_id_;
    handle_ = other.handle_;
    skel_arch_ = other.skel_arch_;
    cached_ = other.cached_;
    cache_flush_ = other.cache_flush_;
    cache_invalidate_ = other.cache_invalidate_;
    allocations_ = std::move(other.allocations_);
    other.handle_ = 0;
  }
  return *this;
}

Result<Arena> HexagonDriver::Alloc(size_t bytes, size_t alignment) {
  if (handle_ == 0) {
    return Error::InvalidState;
  }
  if (alignment == 0 || (alignment & (alignment - 1)) != 0) {
    return Error::InvalidArgument;
  }

  // rpcmem promises no alignment, so over-allocate and trim. The fd and the
  // mapping belong to the base allocation, so nothing may be trimmed below it.
  const size_t total = bytes + alignment;
  if (bytes == 0 || total > static_cast<size_t>(INT_MAX)) {
    return Error::InvalidArgument;
  }

  const uint32_t flags = cached_ ? RPCMEM_DEFAULT_FLAGS : RPCMEM_FLAG_UNCACHED;
  void* base = rpcmem_alloc(RPCMEM_HEAP_ID_SYSTEM, flags, (int)total);
  if (base == nullptr) {
    return Error::MemoryAllocationFailed;
  }

  // Mapping the fd is what lets the DSP turn it back into an address through
  // HAP_mmap_get(); without it the skel cannot reach the buffer at all.
  const int fd = rpcmem_to_fd(base);
  if (fd < 0) {
    rpcmem_free(base);
    return Error::Internal;
  }
  if (fastrpc_mmap(domain_id_, fd, base, 0, total, FASTRPC_MAP_FD) != 0) {
    rpcmem_free(base);
    return Error::Internal;
  }

  void* aligned = reinterpret_cast<void*>(
      (reinterpret_cast<uintptr_t>(base) + alignment - 1) &
      ~(static_cast<uintptr_t>(alignment) - 1));

  allocations_.emplace(aligned, Allocation{base, total, fd});
  return Arena{
      aligned,
      bytes,
      fd,
      static_cast<uint64_t>(
          reinterpret_cast<uintptr_t>(aligned) - reinterpret_cast<uintptr_t>(base))};
}

void HexagonDriver::Free(void* ptr) {
  if (ptr == nullptr) {
    return;
  }
  auto it = allocations_.find(ptr);
  if (it == allocations_.end()) {
    return;
  }
  fastrpc_munmap(domain_id_, it->second.fd, it->second.base, it->second.size);
  rpcmem_free(it->second.base);
  allocations_.erase(it);
}

Error HexagonDriver::Flush(void* ptr, size_t bytes) {
  if (!cached_ || bytes == 0) {
    return Error::Ok;
  }
  return cache_flush_(ptr, (int)bytes) == 0 ? Error::Ok : Error::Internal;
}

Error HexagonDriver::Invalidate(void* ptr, size_t bytes) {
  if (!cached_ || bytes == 0) {
    return Error::Ok;
  }
  return cache_invalidate_(ptr, (int)bytes) == 0 ? Error::Ok : Error::Internal;
}

Error HexagonDriver::ExecuteCommandGroup(
    int group_fd,
    int group_offset,
    uint32_t count,
    int sync_fd,
    int sync_offset,
    int sync_size) {
  if (handle_ == 0) {
    return Error::InvalidState;
  }
  const AEEResult code = htp_ops_execute_command_group(
      handle_,
      group_fd,
      group_offset,
      (int)count,
      sync_fd,
      sync_offset,
      sync_size);
  if (code == AEE_EEXPIRED || code == kAeeExpiredDsp) {
    ProbeAfterTimeout(*this, domain_id_, handle_, code);
  }
  return ToError(code, "execute_command_group");
}

Error HexagonDriver::ExecuteCommandGroupTraced(
    int group_fd,
    int group_offset,
    uint32_t count,
    int sync_fd,
    int sync_offset,
    int sync_size,
    int profile_fd,
    int profile_offset,
    int profile_size) {
  if (handle_ == 0) {
    return Error::InvalidState;
  }
  const AEEResult code = htp_ops_execute_command_group_profile(
      handle_,
      group_fd,
      group_offset,
      (int)count,
      sync_fd,
      sync_offset,
      sync_size,
      profile_fd,
      profile_offset,
      profile_size);
  if (code == AEE_EEXPIRED || code == kAeeExpiredDsp) {
    ProbeAfterTimeout(*this, domain_id_, handle_, code);
  }
  return ToError(code, "execute_command_group_profile");
}

SharedArenaPool& SharedArenaPool::Get() {
  static SharedArenaPool pool;
  return pool;
}

Result<Arena> SharedArenaPool::Acquire(size_t bytes) {
  const auto existing = arenas_.find(bytes);
  if (existing != arenas_.end()) {
    return existing->second;
  }

  if (driver_ == nullptr) {
    auto driver = HexagonDriver::Create();
    if (!driver.ok()) {
      return driver.error();
    }
    driver_ = std::make_unique<HexagonDriver>(std::move(driver.get()));
  }

  auto arena = driver_->Alloc(bytes);
  if (!arena.ok()) {
    return arena.error();
  }
  std::fprintf(
      stderr, "[hexagon] pool: new block %zu bytes (#%zu)\n", bytes, arenas_.size() + 1);
  // The heap hands back whatever was there before, and the first execute of a
  // model expects the zeroed scratch every delegate used to get of its own.
  std::memset(arena.get().ptr, 0, bytes);
  arenas_.emplace(bytes, arena.get());
  return arena.get();
}

Error HexagonDriver::PowerAcquire() {
  return ToError(htp_ops_power_acquire(handle_), "power_acquire");
}

Error HexagonDriver::PowerRelease() {
  return ToError(htp_ops_power_release(handle_), "power_release");
}

} // namespace executorch::backends::hexagon
