/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include <executorch/backends/hexagon/runtime/hexagon_driver.h>

#include <climits>
#include <cstdio>
#include <cstring>

#include <dlfcn.h>

#include <AEEStdErr.h>
#include <dsp_capabilities_utils.h>
#include <remote.h>
#include <rpcmem.h>

// Generated by qaic from the same IDL the skel is built from, so the handle
// numbers on both sides cannot drift.
#include "htp_ops.h"

namespace executorch::backends::hexagon {

namespace {

constexpr const char* kSkelUriPrefix = "file:///";
constexpr const char* kSkelUriSuffix = "?htp_ops_skel_handle_invoke&_modver=1.0";
// Must match the skel target's OUTPUT_NAME in skel/CMakeLists.txt.
// The capability's low byte holds the arch as hex digits, so v79 arrives as
// 0x79 and has to be printed back as "79" -- %u would ask for v121.
constexpr const char* kSkelNameFormat = "libhex-htp-skel-v%02X.so";
constexpr const char* kDsprpcLib = "libcdsprpc.so";

Error ToError(AEEResult err, const char* what) {
  if (err == AEE_SUCCESS) {
    return Error::Ok;
  }
  std::fprintf(stderr, "[hexagon] %s failed: 0x%08x\n", what, (unsigned)err);
  return Error::Internal;
}

// Picks the skel matching the device's Hexagon arch. A mismatched skel would
// run kernels compiled for a different HVX width, which shows up as corrupted
// numbers rather than a load failure, so the arch is verified after loading.
std::string SelectSkel(int domain_id, uint32_t* expected_arch) {
  uint32_t capability = 0;
  *expected_arch = 0;

  int err = get_hex_arch_ver(domain_id, &capability);
  unsigned int arch = capability & 0xff;
  if (err != AEE_SUCCESS || arch == 0) {
    std::fprintf(
        stderr,
        "[hexagon] get_hex_arch_ver failed: 0x%08x capability=0x%x\n",
        (unsigned)err,
        capability);
    return std::string();
  }

  *expected_arch = arch;
  char name[64];
  std::snprintf(name, sizeof(name), kSkelNameFormat, arch);
  return name;
}

} // namespace

void HexagonDriver::ResolveCacheOps() {
  void* lib = dlopen(kDsprpcLib, RTLD_NOW | RTLD_LOCAL);
  if (lib == nullptr) {
    std::fprintf(
        stderr, "[hexagon] dlopen(%s) failed: %s\n", kDsprpcLib, dlerror());
    return;
  }
  cache_flush_ = reinterpret_cast<CacheOpFn>(dlsym(lib, "rpcmem_cache_flush"));
  cache_invalidate_ =
      reinterpret_cast<CacheOpFn>(dlsym(lib, "rpcmem_cache_invalidate"));
  cached_ = cache_flush_ != nullptr && cache_invalidate_ != nullptr;
  // The library stays loaded for the process: the FastRPC handle is backed by
  // it and dlclosing it here would strand the session.
}

Result<HexagonDriver> HexagonDriver::Create(int domain_id) {
  HexagonDriver driver;
  driver.domain_id_ = domain_id;
  ET_CHECK_OK_OR_RETURN_ERROR(driver.Open());
  return driver;
}

Error HexagonDriver::Open() {
  domain* dsp_domain = get_domain(domain_id_);
  if (dsp_domain == nullptr) {
    std::fprintf(stderr, "[hexagon] no domain %d on this device\n", domain_id_);
    return Error::Internal;
  }

  const std::string skel_name = SelectSkel(domain_id_, &skel_arch_);
  if (skel_name.empty()) {
    return Error::Internal;
  }
  const std::string uri = std::string(kSkelUriPrefix) + skel_name +
      kSkelUriSuffix + dsp_domain->uri;

  // The skel is unsigned, so FastRPC has to put the session in an unsigned
  // protection domain before the module is loaded. Without this the DSP
  // rejects the load with AEE_EFAILED (0xffffffff).
  {
    remote_rpc_control_unsigned_module unsigned_pd;
    unsigned_pd.domain = domain_id_;
    unsigned_pd.enable = 1;
    const AEEResult pd_err = remote_session_control(
        DSPRPC_CONTROL_UNSIGNED_MODULE, &unsigned_pd, sizeof(unsigned_pd));
    if (pd_err != AEE_SUCCESS) {
      std::fprintf(
          stderr,
          "[hexagon] failed to enable the unsigned protection domain on domain "
          "%d: 0x%08x\n",
          domain_id_,
          (unsigned)pd_err);
      return Error::Internal;
    }
  }

  AEEResult err = htp_ops_open(uri.c_str(), &handle_);
  if (err != AEE_SUCCESS) {
    std::fprintf(
        stderr,
        "[hexagon] failed to load skel %s: 0x%08x\n",
        skel_name.c_str(),
        (unsigned)err);
    handle_ = 0;
    return Error::Internal;
  }

  uint32_t reported_arch = 0;
  err = htp_ops_get_skel_arch(handle_, &reported_arch);
  if (err != AEE_SUCCESS || reported_arch != skel_arch_) {
    std::fprintf(
        stderr,
        "[hexagon] skel arch mismatch: device V%02X, skel V%02X\n",
        skel_arch_,
        reported_arch);
    Close();
    return Error::Internal;
  }

  // Without a latency hint the DSP is parked between ops and per-op latency
  // dominates.
  struct remote_rpc_control_latency latency;
  latency.enable = RPC_PM_QOS;
  latency.latency = 50;
  err = remote_handle64_control(
      handle_, DSPRPC_CONTROL_LATENCY, &latency, sizeof(latency));
  if (err != AEE_SUCCESS) {
    std::fprintf(
        stderr, "[hexagon] RPC_PM_QOS unavailable: 0x%08x\n", (unsigned)err);
  }

  ResolveCacheOps();

  ET_CHECK_OK_OR_RETURN_ERROR(
      ToError(htp_ops_init_backend(handle_), "init_backend"));
  return Error::Ok;
}

void HexagonDriver::Close() {
  for (auto& entry : allocations_) {
    const Allocation& alloc = entry.second;
    fastrpc_munmap(domain_id_, alloc.fd, alloc.base, alloc.size);
    rpcmem_free(alloc.base);
  }
  allocations_.clear();

  if (handle_ != 0) {
    htp_ops_close(handle_);
    handle_ = 0;
  }
}

HexagonDriver::~HexagonDriver() {
  Close();
}

HexagonDriver::HexagonDriver(HexagonDriver&& other) noexcept
    : domain_id_(other.domain_id_),
      handle_(other.handle_),
      skel_arch_(other.skel_arch_),
      cached_(other.cached_),
      cache_flush_(other.cache_flush_),
      cache_invalidate_(other.cache_invalidate_),
      allocations_(std::move(other.allocations_)) {
  other.handle_ = 0;
}

HexagonDriver& HexagonDriver::operator=(HexagonDriver&& other) noexcept {
  if (this != &other) {
    Close();
    domain_id_ = other.domain_id_;
    handle_ = other.handle_;
    skel_arch_ = other.skel_arch_;
    cached_ = other.cached_;
    cache_flush_ = other.cache_flush_;
    cache_invalidate_ = other.cache_invalidate_;
    allocations_ = std::move(other.allocations_);
    other.handle_ = 0;
  }
  return *this;
}

Result<void*> HexagonDriver::Alloc(size_t bytes, size_t alignment) {
  if (handle_ == 0) {
    return Error::InvalidState;
  }
  if (alignment == 0 || (alignment & (alignment - 1)) != 0) {
    return Error::InvalidArgument;
  }

  // rpcmem promises no alignment, so over-allocate and trim. The fd and the
  // mapping belong to the base allocation, so nothing may be trimmed below it.
  const size_t total = bytes + alignment;
  if (bytes == 0 || total > static_cast<size_t>(INT_MAX)) {
    return Error::InvalidArgument;
  }

  const uint32_t flags = cached_ ? RPCMEM_DEFAULT_FLAGS : RPCMEM_FLAG_UNCACHED;
  void* base = rpcmem_alloc(RPCMEM_HEAP_ID_SYSTEM, flags, (int)total);
  if (base == nullptr) {
    return Error::MemoryAllocationFailed;
  }

  // Mapping the fd is what lets the DSP turn it back into an address through
  // HAP_mmap_get(); without it the skel cannot reach the buffer at all.
  const int fd = rpcmem_to_fd(base);
  if (fd < 0) {
    rpcmem_free(base);
    return Error::Internal;
  }
  if (fastrpc_mmap(domain_id_, fd, base, 0, total, FASTRPC_MAP_FD) != 0) {
    rpcmem_free(base);
    return Error::Internal;
  }

  void* aligned = reinterpret_cast<void*>(
      (reinterpret_cast<uintptr_t>(base) + alignment - 1) &
      ~(static_cast<uintptr_t>(alignment) - 1));

  allocations_.emplace(aligned, Allocation{base, total, fd});
  return aligned;
}

void HexagonDriver::Free(void* ptr) {
  if (ptr == nullptr) {
    return;
  }
  auto it = allocations_.find(ptr);
  if (it == allocations_.end()) {
    return;
  }
  fastrpc_munmap(domain_id_, it->second.fd, it->second.base, it->second.size);
  rpcmem_free(it->second.base);
  allocations_.erase(it);
}

Result<int> HexagonDriver::ToFd(void* ptr) {
  auto it = allocations_.find(ptr);
  if (it == allocations_.end()) {
    return Error::InvalidArgument;
  }
  return it->second.fd;
}

Result<uint64_t> HexagonDriver::MappingOffset(void* ptr) {
  auto it = allocations_.find(ptr);
  if (it == allocations_.end()) {
    return Error::InvalidArgument;
  }
  return static_cast<uint64_t>(
      reinterpret_cast<uintptr_t>(ptr) -
      reinterpret_cast<uintptr_t>(it->second.base));
}

Error HexagonDriver::Flush(void* ptr, size_t bytes) {
  if (!cached_ || bytes == 0) {
    return Error::Ok;
  }
  return cache_flush_(ptr, (int)bytes) == 0 ? Error::Ok : Error::Internal;
}

Error HexagonDriver::Invalidate(void* ptr, size_t bytes) {
  if (!cached_ || bytes == 0) {
    return Error::Ok;
  }
  return cache_invalidate_(ptr, (int)bytes) == 0 ? Error::Ok : Error::Internal;
}

Error HexagonDriver::ExecuteCommandGroup(
    int group_fd,
    int group_offset,
    uint32_t count,
    int sync_fd,
    int sync_offset,
    int sync_size) {
  if (handle_ == 0) {
    return Error::InvalidState;
  }
  return ToError(
      htp_ops_execute_command_group(
          handle_,
          group_fd,
          group_offset,
          (int)count,
          sync_fd,
          sync_offset,
          sync_size),
      "execute_command_group");
}

Error HexagonDriver::PowerAcquire() {
  return ToError(htp_ops_power_acquire(handle_), "power_acquire");
}

Error HexagonDriver::PowerRelease() {
  return ToError(htp_ops_power_release(handle_), "power_release");
}

} // namespace executorch::backends::hexagon
