# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Hexagon-sim evidence for the bounded tensor-tensor power subset."""

import numpy as np
import torch
from torch.export import export

from executorch.backends.hexagon import hexagon_ops
from executorch.backends.hexagon.partition.hexagon_partitioner import HexagonPartitioner
from executorch.backends.hexagon.test.blob_interpreter import Arena, read_blob
from executorch.exir import EdgeCompileConfig, to_edge_transform_and_lower

import hexagon_sim
from test_blob_on_sim import _RUNNER, _SCHEMA, _SOURCES, _HT_P_OP_SHIM


class StaticPower(torch.nn.Module):
    def __init__(self, base, exponent):
        super().__init__()
        self.base = base
        self.exponent = exponent

    def forward(self):
        return torch.pow(
            torch.tensor(self.base, dtype=torch.float16),
            torch.tensor(self.exponent, dtype=torch.float16),
        )


def _blob(base, exponent):
    program = to_edge_transform_and_lower(
        export(StaticPower(base, exponent), ()),
        partitioner=[HexagonPartitioner()],
        compile_config=EdgeCompileConfig(_check_ir_validity=False),
    ).exported_program()
    call = next(
        node
        for node in program.graph_module.graph.nodes
        if node.target is torch.ops.higher_order.executorch_call_delegate
    )
    inner = program.graph_module.get_submodule(call.args[0].target)
    blob = bytes(inner._processed_bytes)
    return blob, read_blob(blob)[1]


def test_tensor_tensor_power_runs_on_hexagon_sim():
    hexagon_sim._check()
    base = (torch.arange(65, dtype=torch.float32) / 8.0 + 0.25).tolist()
    cases = []
    for tag, exponent in (("W1", 1), ("W2", 2), ("W3", 3), ("W4", 4), ("W0", 0), ("WM", -1)):
        blob, commands = _blob(base, exponent)
        cases.append((tag, blob, commands))

    lines = ["// Generated by test_pow_tensor_tensor_on_sim.py."]
    for index, (_, blob, _) in enumerate(cases):
        blob_body = ",".join(str(byte) for byte in blob)
        lines.append(
            "static const unsigned char kBlob%d[] = {%s};" % (index, blob_body)
        )
        lines.append(
            "static const unsigned char kInputData%d[] = {0};" % index
        )
    lines.append("static const BlobFixture kFixtures[] = {")
    arena_bytes = 0
    for index, (tag, blob, _) in enumerate(cases):
        header, _ = read_blob(blob)
        arena_bytes = max(arena_bytes, len(Arena(header, blob, "pow-sim").bytes))
        lines.append(
            '  {"%s", kBlob%d, sizeof(kBlob%d), kInputData%d, sizeof(kInputData%d), 0},'
            % (tag, index, index, index, index)
        )
    lines.append("};")
    lines.append("static const unsigned kFixtureCount = %d;" % len(cases))
    lines.append("static const unsigned kMaxArenaBytes = %d;" % arena_bytes)

    simulated = hexagon_sim.run(
        _RUNNER,
        _SOURCES,
        headers={
            "blob_fixture.h": "\n".join(lines) + "\n",
            "htp_ops.h": _HT_P_OP_SHIM,
        },
        includes_more=[str(_SCHEMA)],
    )
    assert "Main() returned 0" in hexagon_sim.LAST_STDOUT
    mapping = {v: k for k, v in vars(hexagon_ops).items() if k.startswith("DSP_OP_")}
    blit = hexagon_ops.DSP_OP_RASTER_BLIT
    binary = hexagon_ops.DSP_OP_BINARY_ELEMENTWISE
    # The clone emitter the elementwise branch admits writes both lifted constants
    # with raster blits before the power itself. Exponent one is the identity, so
    # its power command collapses to a third blit instead of a binary: the first
    # two place the base and exponent, the third copies the base through. Every
    # other case computes the power with one binary elementwise, and exponents
    # three and four add one binary each because the emitter walks them as
    # repeated multiplies rather than a loop. The host sibling
    # test_pow_tensor_tensor.py describes the same prefix, but each twin needs its
    # own measured list so neither can drift silently under the other.
    expected_types = {
        "W1": [blit, blit, blit],
        "W2": [blit, blit, binary],
        "W3": [blit, blit, binary, binary],
        "W4": [blit, blit, binary, binary, binary],
        "W0": [blit, blit, binary],
        "WM": [blit, blit, binary],
    }
    reference_base = torch.tensor(base, dtype=torch.float64)
    for tag, _, commands in cases:
        types = [command.type for command in commands]
        assert types == expected_types[tag], (tag, types)
        assert types[:2] == [blit, blit], f"{tag}: the two constant blits are not leading"
        compute = types.index(binary) if binary in types else len(types)
        assert all(kind == blit for kind in types[:compute]), (
            f"{tag}: a blit follows the power computation: {types}"
        )
        assert {mapping[command.type] for command in commands} <= {
            "DSP_OP_RASTER_BLIT",
            "DSP_OP_BINARY_ELEMENTWISE",
        }
        bits = simulated[f"{tag}0"]
        assert bits and any(bit != 0 for bit in bits)
        actual = torch.from_numpy(
            np.asarray(bits, dtype=np.uint16).view(np.float16).copy()
        ).double()
        exponent = {"W1": 1, "W2": 2, "W3": 3, "W4": 4, "W0": 0, "WM": -1}[tag]
        reference = reference_base.pow(exponent)
        torch.testing.assert_close(actual, reference, rtol=2e-3, atol=2e-3)
