# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""The fixed-window adaptive average cases through the real pool blob."""

import os
import pathlib
import sys

import numpy as np
import pytest
import torch

# Resolve this checkout rather than the editable install in the environment.
sys.path.insert(0, os.fspath(pathlib.Path(__file__).resolve().parents[4]))
sys.path.insert(0, os.fspath(pathlib.Path(__file__).resolve().parent))

import hexagon_sim  # noqa: E402
from blob_interpreter import read_blob  # noqa: E402
from executorch.backends.hexagon import hexagon_ops  # noqa: E402
from executorch.backends.hexagon.partition.hexagon_partitioner import (  # noqa: E402
    HexagonPartitioner,
)
from executorch.exir import (  # noqa: E402
    EdgeCompileConfig,
    to_edge,
    to_edge_transform_and_lower,
)
from executorch.exir.dialects._ops import ops as exir_ops  # noqa: E402
from torch.export import export  # noqa: E402

_RUNNER = pathlib.Path(__file__).resolve().parent / "sim/adaptive_pool_runner.cpp"
_SCHEMA = pathlib.Path(__file__).resolve().parents[1] / "serialization"
_SOURCES = [
    "blit_ops.cc",
    "pool_ops.cc",
    "ops/pool_fp16.c",
    "worker_pool.cc",
    "vtcm_mgr.cc",
    "pwl.cc",
    "eltwise_ops.cc",
    str(pathlib.Path(__file__).resolve().parent / "sim/htp_probe_stage_shim.cc"),
]
_CASES = (
    (63, 63, 21, 21, "AP63"),
    (64, 64, 32, 32, "AP64"),
    (65, 65, 13, 13, "AP65"),
    (8, 12, 2, 3, "APMIX"),
    (8, 12, 8, 12, "APID"),
    (8, 12, 1, 3, "APONEAXIS"),
    (8, 8, 1, 1, "APONE"),
)


class _Adaptive(torch.nn.Module):
    def __init__(self, output):
        super().__init__()
        self.output = output

    def forward(self, x):
        return torch.nn.functional.adaptive_avg_pool2d(x, self.output)


def _lower(output, x):
    exported = export(_Adaptive(output), (x,))
    edge = to_edge(
        exported, compile_config=EdgeCompileConfig(_check_ir_validity=False)
    ).exported_program()
    edge_names = {
        node.name
        for node in edge.graph_module.graph.nodes
        if node.op == "call_function"
    }
    program = to_edge_transform_and_lower(
        exported,
        partitioner=[HexagonPartitioner()],
        compile_config=EdgeCompileConfig(_check_ir_validity=False),
    ).exported_program()
    calls = [
        node
        for node in program.graph_module.graph.nodes
        if node.target is torch.ops.higher_order.executorch_call_delegate
    ]
    assert len(calls) == 1
    delegate = program.graph_module.get_submodule(calls[0].args[0].target)
    delegate_names = {
        node.name
        for node in delegate.original_module.graph_module.graph.nodes
        if node.op == "call_function"
    }
    assert delegate_names == edge_names
    blob = bytes(delegate._processed_bytes)
    return blob


def _fixture_header(fixtures):
    lines = ["// Generated by test_adaptive_pool_sim.py."]
    for index, (tag, blob, inputs) in enumerate(fixtures):
        for name, data in (("Blob", blob), ("InputData", inputs)):
            body = ",".join(str(byte) for byte in data)
            lines.append(f"static const unsigned char k{name}{index}[] = {{{body}}};")
    lines.append("static const BlobFixture kFixtures[] = {")
    for index, (tag, blob, inputs) in enumerate(fixtures):
        lines.append(
            f'  {{"{tag}", kBlob{index}, sizeof(kBlob{index}), '
            f"kInputData{index}, sizeof(kInputData{index}), 0}},"
        )
    lines.append("};")
    lines.append("static const unsigned kFixtureCount = sizeof(kFixtures) / sizeof(kFixtures[0]);")
    return "\n".join(lines) + "\n"


def _input(ih, iw):
    values = torch.arange(64 * ih * iw, dtype=torch.float64)
    values = ((values % 17) - 8).reshape(1, 64, ih, iw) / 8
    return values.to(torch.float16)


def _one_ulp_or_zero(actual, reference):
    expected = reference.astype(np.float16)
    down = np.nextafter(expected, np.float16(-np.inf))
    up = np.nextafter(expected, np.float16(np.inf))
    return np.all((actual == expected) | (actual == down) | (actual == up))


def test_fixed_adaptive_average_cases_on_hexagon_sim():
    try:
        hexagon_sim._check()
    except hexagon_sim.Unavailable as error:
        pytest.skip(str(error))

    fixtures = []
    command_names = {
        value: name
        for name, value in vars(hexagon_ops).items()
        if name.startswith("DSP_OP_")
    }
    for ih, iw, oh, ow, tag in _CASES:
        x = _input(ih, iw)
        blob = _lower((oh, ow), x)
        _, commands = read_blob(blob)
        names = [command_names[command.type] for command in commands]
        if tag == "APONE":
            assert names == ["DSP_OP_REDUCTION"]
        else:
            assert names == [
                "DSP_OP_RASTER_BLIT",
                "DSP_OP_POOL2D_FP16",
                "DSP_OP_RASTER_BLIT",
            ]
        fixtures.append((tag, blob, x.numpy().tobytes()))

    results = hexagon_sim.run(
        _RUNNER,
        _SOURCES,
        headers={
            "blob_fixture.h": _fixture_header(fixtures),
            "htp_ops.h": "/* Empty on purpose; see test_blob_on_sim.py. */\n",
        },
        includes_more=[str(_SCHEMA)],
    )
    for ih, iw, oh, ow, tag in _CASES:
        words = results[f"{tag}0"]
        assert words
        actual = np.asarray(words, dtype=np.uint16).view(np.float16)
        reference = torch.nn.functional.adaptive_avg_pool2d(
            _input(ih, iw).double(), (oh, ow)
        ).numpy().reshape(-1)
        assert actual.size == reference.size
        assert _one_ulp_or_zero(actual, reference), (
            f"{tag}: max error {np.max(np.abs(actual.astype(np.float64) - reference))}"
        )
